spring:
  application:
    name: api-library-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

app:
  api:
    book-service: "api-book-service"
    user-service: "api-user-service"
